# Generated by Django 4.2.6 on 2023-11-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_image_product_cover_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, upload_to='products/download/<django.db.models.fields.CharField>'),
        ),
    ]
