# Generated by Django 4.2.6 on 2023-11-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.SlugField(blank=True, max_length=32),
        ),
    ]
