# Generated by Django 4.2.6 on 2023-11-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.SlugField(blank=True, max_length=32, null=True),
        ),
    ]
