# Generated by Django 4.2.6 on 2023-11-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='url',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
