# Generated by Django 4.2.6 on 2023-11-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
